### ISSUE TITLE
No plus icon when type: Array

### ISSUE THREAD

**Issue by benjick** [djhi/meteor-autoform-materialize#3]
Hi

When using your package there is no plus icon on the button for adding more fields.

See http://autoform.meteor.com/quickform and select _Optional array of strings_

**Comment by djhi** [comment]
Thx for pointing that out. I'll correct it asap

**Comment by djhi** [comment]
Should be fixed in 0.0.8

**Comment by Sivli-Embir** [comment]
This seems to still be an issue, with the following schema:

``` js
  emails: {
    type: [String],
    label: function () { return TAPi18n.__("emailAddresses") },
    regEx: SimpleSchema.RegEx.Email
  }
```

It outputs bootstrap code:

``` html
<div class="panel panel-default">
  <div class="panel-heading">Email Addresses</div>
  <ul class="list-group">
    <li class="list-group-item autoform-array-item">
      <div>
        <div class="autoform-remove-item-wrap">
          <button type="button" class="btn btn-primary autoform-remove-item"><span class="glyphicon glyphicon-minus"></span></button>
        </div>
        <div class="autoform-array-item-body">
          <div class="form-group"> 
            <input type="text" name="emails.0" id="afYJPsCTv6aFjG7vw" data-schema-key="emails.0" class="form-control">    
            <span class="help-block"></span>
          </div>    
        </div>
      </div>
    </li>
    <li class="list-group-item">
      <button type="button" class="btn btn-primary autoform-add-item" data-autoform-field="emails"><span class="glyphicon glyphicon-plus"></span></button>
    </li>
  </ul>
</div>
```

This is running:
aldeed:autoform@5.1.1
gildaspk:autoform-materialize@0.0.14

**Comment by djhi** [comment]
Are you sure you set the correct template ?

I updated the playground repo to include your emails property, (again without the label function, I use tapii18n myself but I want to keep the playground simple), and it works fine.

Btw, you might be interested by this: https://github.com/djhi/meteor-simpleschema-tapi18n-labels

**Comment by cicely-f** [comment]
This still seems to be an issue:
I'm using the following packages:
- aldeed:autoform 5.1.2
- materialize:materialize 0.96.1
- gildaspk:autoform-materialize 0.0.18
- gildaspk:autoform-modal-materialize 0.0.6

With a field like this:

``` javascript
  targetLanguages: {
    type: [String],
    label: "Target languages",
    min: 1
  }
```

I still get references to glyphicons for the add/remove buttons instead of the expected mdi-\* icons.

**Comment by elie222** [comment]
Still an issue for me too

**Comment by elie222** [comment]
It isn't actually an issue. I wasn't using:
AutoForm.setDefaultTemplate('materialize');
