### ISSUE TITLE
Error when using pickadate

### ISSUE THREAD

**Issue by coniel** [djhi/meteor-autoform-materialize#7]
I'm getting the following error:

``` javascript
Exception in template helper: ReferenceError: atts is not defined
    at Object.AutoForm.addInputType.valueIn (http://localhost:3000/packages/gildaspk_autoform-materialize.js?42f987a371dc61ee9d1422c7be8927d3e00d78d1:1119:18)
    at getInputValue (http://localhost:3000/packages/aldeed_autoform.js?b2b90d28d5cc29be68358bb3c8bb8a337992a7dd:1881:22)
    at Object.afFieldInputContext (http://localhost:3000/packages/aldeed_autoform.js?b2b90d28d5cc29be68358bb3c8bb8a337992a7dd:6028:17)
    at bindDataContext (http://localhost:3000/packages/blaze.js?4e49999979a58da0e2265f7bd3f5910f9901b07b:2786:16)
    at Blaze._wrapCatchingExceptions (http://localhost:3000/packages/blaze.js?4e49999979a58da0e2265f7bd3f5910f9901b07b:1607:16)
    at http://localhost:3000/packages/blaze.js?4e49999979a58da0e2265f7bd3f5910f9901b07b:2834:66
    at Function.Template._withTemplateInstanceFunc (http://localhost:3000/packages/blaze.js?4e49999979a58da0e2265f7bd3f5910f9901b07b:3382:12)
    at wrapHelper (http://localhost:3000/packages/blaze.js?4e49999979a58da0e2265f7bd3f5910f9901b07b:2833:27)
    at Spacebars.call (http://localhost:3000/packages/spacebars.js?7bafbe05ec09b6bbb6a3b276537e4995ab298a2f:172:18)
    at Spacebars.mustacheImpl (http://localhost:3000/packages/spacebars.js?7bafbe05ec09b6bbb6a3b276537e4995ab298a2f:109:25)
```

When using:

```
{{> afFieldInput name='endDate' type="pickadate"}}
```

**Comment by djhi** [comment]
I'll check that today. Thx for reporting it

**Comment by djhi** [comment]
Fixed in `0.0.11`

**Comment by coniel** [comment]
Thanks, although I'm getting this now:

``` javascript
Exception from Tracker afterFlush function: Cannot read property 'format' of undefined
TypeError: Cannot read property 'format' of undefined
    at http://localhost:3000/packages/underscore.js?0a80a8623e1b40b5df5a05582f288ddd586eaa18:931:18
    at Array.forEach (native)
    at _.each._.forEach (http://localhost:3000/packages/underscore.js?0a80a8623e1b40b5df5a05582f288ddd586eaa18:156:11)
    at Function._.defaults (http://localhost:3000/packages/underscore.js?0a80a8623e1b40b5df5a05582f288ddd586eaa18:928:5)
    at Template.afPickadate.rendered (http://localhost:3000/packages/gildaspk_autoform-materialize.js?eb6c2a187bfe9462c8a0da6f1c89326181f62464:1232:12)
    at runTemplateHooks (http://localhost:3000/packages/aldeed_template-extension.js?2e25a48119980b3ff2fba34bcf67b18deac45199:415:10)
    at templateExtensionMasterHook (http://localhost:3000/packages/aldeed_template-extension.js?2e25a48119980b3ff2fba34bcf67b18deac45199:364:5)
    at http://localhost:3000/packages/blaze.js?4e49999979a58da0e2265f7bd3f5910f9901b07b:3061:22
    at Function.Template._withTemplateInstanceFunc (http://localhost:3000/packages/blaze.js?4e49999979a58da0e2265f7bd3f5910f9901b07b:3382:12)
    at fireCallbacks (http://localhost:3000/packages/blaze.js?4e49999979a58da0e2265f7bd3f5910f9901b07b:3057:12)
```

**Comment by djhi** [comment]
next version (`0.0.12`) should be ok. Sorry about that, I don't use the pickadate either and tests are inexistant for now. I'll add some when I'll get the time.

**Comment by coniel** [comment]
Thanks a lot, it works now. Although I'm still getting an error in the console:

``` javascript
Exception from Tracker afterFlush function: undefined is not a function
TypeError: undefined is not a function
    at null.<anonymous> (http://localhost:3000/packages/gildaspk_autoform-materialize.js?931db8483b10106c76992913e13b3e3a2beaf290:1251:14)
    at http://localhost:3000/packages/blaze.js?4e49999979a58da0e2265f7bd3f5910f9901b07b:1821:18
    at Function.Template._withTemplateInstanceFunc (http://localhost:3000/packages/blaze.js?4e49999979a58da0e2265f7bd3f5910f9901b07b:3382:12)
    at http://localhost:3000/packages/blaze.js?4e49999979a58da0e2265f7bd3f5910f9901b07b:1820:29
    at Object.Blaze._withCurrentView (http://localhost:3000/packages/blaze.js?4e49999979a58da0e2265f7bd3f5910f9901b07b:2105:12)
    at viewAutorun (http://localhost:3000/packages/blaze.js?4e49999979a58da0e2265f7bd3f5910f9901b07b:1819:18)
    at Tracker.Computation._compute (http://localhost:3000/packages/tracker.js?21f0f4306879f57e10ad3a97efe9ea521c5b5775:308:36)
    at new Tracker.Computation (http://localhost:3000/packages/tracker.js?21f0f4306879f57e10ad3a97efe9ea521c5b5775:224:10)
    at Object.Tracker.autorun (http://localhost:3000/packages/tracker.js?21f0f4306879f57e10ad3a97efe9ea521c5b5775:499:11)
    at Blaze.View.autorun (http://localhost:3000/packages/blaze.js?4e49999979a58da0e2265f7bd3f5910f9901b07b:1831:22)
```

**Comment by djhi** [comment]
Fix on its way

**Comment by sakulstra** [comment]
Hay there, I still get an error like this:

``` js
Exception from Tracker afterFlush function:
debug.js:41 TypeError: Cannot read property 'get' of undefined
    at AutoForm.addInputType.valueOut (gildaspk_autoform-materialize.js:2114)
    at Object.autoFormGetInputValue [as getInputValue] (autoform-api.js:516)
    at HTMLInputElement.<anonymous> (autoform-inputs.js:6)
    at Function.jQuery.extend.each (jquery.js:384)
    at jQuery.fn.jQuery.each (jquery.js:136)
    at getFlatDocOfFieldValues (autoform-inputs.js:5)
    at Object.autoFormGetFormValues [as getFormValues] (autoform-api.js:314)
    at Object.autoFormGetFieldValue [as getFieldValue] (autoform-api.js:429)
    at null.<anonymous> (gildaspk_autoform-materialize.js:2626)
    at view.js:199
```

Someone has an idea what the problem could be?
I'm using this package inside another package.

Everything works like expected ... it's just spamming the console.
perhaps one could simply rewrite

``` js
item = this.pickadate('picker').get('select');
//to
item = this.pickadate('picker');
if(item) item = item.get('select');
//most likely a bad solution
```

Regards,
Lukas
